from __future__ import annotations

import html
import json
from dataclasses import asdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable

from auditor.engine.models import FindingRecord, ScanOptions, ScanSummary


def build_report_payload(findings: Iterable[FindingRecord], summary: ScanSummary, options: ScanOptions, spec_info: dict) -> dict:
    return {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "target": options.base_url,
        "spec": spec_info,
        "scope": {
            "allowed_hosts": sorted(options.allowed_hosts),
            "allow_write_methods": options.allow_write_methods,
            "requests_per_second": options.requests_per_second,
            "max_requests": options.max_requests,
        },
        "summary": asdict(summary),
        "findings": [asdict(f) for f in findings],
        "disclaimer": "Automated findings are heuristics and require human validation. Test only systems you own or are explicitly authorized to assess.",
    }


def render_html_report(payload: dict) -> str:
    findings = payload.get("findings", [])
    rows = []
    for f in findings:
        evidence = html.escape(json.dumps(f.get("evidence", {}), indent=2, ensure_ascii=False))
        rows.append(f"""
        <article class=\"finding {html.escape(f['severity'])}\">
          <div class=\"finding-head\"><span class=\"badge\">{html.escape(f['severity'].upper())}</span><h3>{html.escape(f['title'])}</h3></div>
          <p class=\"meta\">{html.escape(f['method'])} {html.escape(f['endpoint'])} · confidence {html.escape(f['confidence'])}</p>
          <p>{html.escape(f['description'])}</p>
          <details><summary>Evidence</summary><pre>{evidence}</pre></details>
          <p><strong>Remediation:</strong> {html.escape(f['remediation'])}</p>
          <p class=\"owasp\">{html.escape(f.get('owasp',''))}</p>
        </article>""")
    summary = payload.get("summary", {})
    counts = summary.get("severity_counts", {})
    cards = "".join(f"<div class='card'><b>{html.escape(k.title())}</b><span>{v}</span></div>" for k, v in counts.items())
    return f"""<!doctype html>
<html><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">
<title>API Security Audit Report</title>
<style>
:root{{--bg:#07101f;--panel:#0d1930;--line:#1b3156;--text:#e8f0ff;--muted:#93a5c7;--accent:#6aa6ff}}
*{{box-sizing:border-box}} body{{margin:0;background:linear-gradient(180deg,#07101f,#0a1223);color:var(--text);font:15px/1.5 Inter,Segoe UI,sans-serif}}
main{{max-width:1120px;margin:auto;padding:40px 24px 80px}} h1{{font-size:34px;margin:6px 0}} .eyebrow{{color:#73b3ff;text-transform:uppercase;letter-spacing:.14em;font-size:12px}}
.meta,.owasp{{color:var(--muted)}} .cards{{display:grid;grid-template-columns:repeat(auto-fit,minmax(130px,1fr));gap:12px;margin:28px 0}} .card{{background:var(--panel);border:1px solid var(--line);border-radius:14px;padding:18px;display:flex;justify-content:space-between}} .card span{{font-size:26px}}
.finding{{background:var(--panel);border:1px solid var(--line);border-left:5px solid #7387a9;border-radius:14px;padding:20px;margin:16px 0}} .finding.high{{border-left-color:#ff6379}} .finding.medium{{border-left-color:#ffb454}} .finding.low{{border-left-color:#74b9ff}} .finding.critical{{border-left-color:#ff3454}} .finding.info{{border-left-color:#8e9db7}}
.finding-head{{display:flex;align-items:center;gap:12px}} .finding-head h3{{margin:0}} .badge{{font-size:11px;border:1px solid #38517c;padding:4px 8px;border-radius:999px}} pre{{white-space:pre-wrap;overflow:auto;background:#06101e;border-radius:10px;padding:14px}} details{{margin:12px 0}} .notice{{background:#0c2745;border:1px solid #1f5d96;border-radius:12px;padding:14px}}
</style></head><body><main>
<p class=\"eyebrow\">Automated API Security Auditor</p><h1>Security Audit Report</h1>
<p class=\"meta\">Target: {html.escape(payload.get('target',''))}<br>Generated: {html.escape(payload.get('generated_at',''))}</p>
<div class=\"cards\">{cards}</div>
<p class=\"notice\">{html.escape(payload.get('disclaimer',''))}</p>
<section>{''.join(rows) if rows else '<p>No findings were generated by the selected test profile.</p>'}</section>
</main></body></html>"""


def write_report_files(payload: dict, json_path: str | None = None, html_path: str | None = None) -> None:
    if json_path:
        path = Path(json_path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")
    if html_path:
        path = Path(html_path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(render_html_report(payload), encoding="utf-8")
