import {useEffect, useMemo, useState} from 'react';
import {NavLink, Route, Routes, useNavigate, useParams} from 'react-router-dom';
import {Activity, AlertTriangle, Boxes, FileJson, Gauge, LayoutDashboard, Play, Plus, Radar, ScanSearch, ShieldCheck, TerminalSquare} from 'lucide-react';
import {api} from './api';
import type {Finding, Operation, Overview, Project, Scan} from './types';

const sevOrder=['critical','high','medium','low','info'];
function fmtDate(v?:string|null){return v?new Date(v).toLocaleString():'—'}
function Severity({value}:{value:string}){return <span className={`severity severity-${value}`}>{value}</span>}
function Status({value}:{value:string}){return <span className={`status status-${value}`}>{value}</span>}
function StatCard({label,value,icon}:{label:string;value:number|string;icon:any}){const Icon=icon; return <div className="stat-card"><div className="stat-icon"><Icon size={20}/></div><div><span>{label}</span><strong>{value}</strong></div></div>}

function Layout(){
 const items=[['/','Overview',LayoutDashboard],['/projects','Projects',Boxes],['/scan/new','New scan',Radar],['/scans','Scans',Activity],['/findings','Findings',AlertTriangle]] as const;
 return <div className="shell"><aside className="sidebar"><div className="brand"><div className="brand-mark"><ShieldCheck size={24}/></div><div><b>API Auditor</b><small>Security workspace</small></div></div><nav>{items.map(([to,label,Icon])=><NavLink key={to} to={to} end={to==='/'} className={({isActive})=>isActive?'active':''}><Icon size={18}/>{label}</NavLink>)}</nav><div className="sidebar-note"><TerminalSquare size={18}/><div><b>CLI available</b><small>Same engine, terminal workflow</small></div></div></aside><main className="content"><Routes><Route path="/" element={<Dashboard/>}/><Route path="/projects" element={<Projects/>}/><Route path="/projects/:id" element={<ProjectDetail/>}/><Route path="/scan/new" element={<NewScan/>}/><Route path="/scans" element={<Scans/>}/><Route path="/scans/:id" element={<ScanDetail/>}/><Route path="/findings" element={<Findings/>}/></Routes></main></div>
}

function Header({eyebrow,title,subtitle,action}:{eyebrow:string;title:string;subtitle:string;action?:any}){return <div className="page-head"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{subtitle}</p></div>{action}</div>}

function Dashboard(){
 const [data,setData]=useState<Overview|null>(null); const [error,setError]=useState('');
 useEffect(()=>{api.overview().then(setData).catch(e=>setError(e.message))},[]);
 const severity=data?.severity||{};
 return <><Header eyebrow="Security posture" title="Audit overview" subtitle="Authorized API assessment activity, findings, and recent scans." action={<NavLink className="button primary" to="/scan/new"><Play size={16}/>Run scan</NavLink>}/>{error&&<div className="error">{error}</div>}<div className="stats"><StatCard label="Projects" value={data?.projects??0} icon={Boxes}/><StatCard label="Scans" value={data?.scans??0} icon={Activity}/><StatCard label="Findings" value={data?.findings??0} icon={AlertTriangle}/><StatCard label="High + Critical" value={(severity.high||0)+(severity.critical||0)} icon={ShieldCheck}/></div><div className="grid two"><section className="panel"><div className="panel-title"><div><span className="eyebrow">Severity</span><h2>Finding distribution</h2></div></div><div className="severity-bars">{sevOrder.map(s=><div className="bar-row" key={s}><span>{s}</span><div className="bar-track"><i style={{width:`${Math.min(100,(severity[s]||0)*12)}%`}}/></div><b>{severity[s]||0}</b></div>)}</div></section><section className="panel"><div className="panel-title"><div><span className="eyebrow">Workflow</span><h2>Safe scan profile</h2></div></div><div className="workflow"><div><span>01</span><b>Import</b><small>OpenAPI / Swagger</small></div><div><span>02</span><b>Map</b><small>Endpoints + schemas</small></div><div><span>03</span><b>Test</b><small>Controlled mutations</small></div><div><span>04</span><b>Analyze</b><small>Evidence + anomalies</small></div></div></section></div><section className="panel"><div className="panel-title"><div><span className="eyebrow">Activity</span><h2>Recent scans</h2></div><NavLink to="/scans">View all</NavLink></div><ScanTable scans={data?.recent_scans||[]}/></section></>
}

function ScanTable({scans}:{scans:Scan[]}){return <div className="table-wrap"><table><thead><tr><th>ID</th><th>Project</th><th>Target</th><th>Status</th><th>Progress</th><th>Created</th></tr></thead><tbody>{scans.map(s=><tr key={s.id}><td><NavLink to={`/scans/${s.id}`}>#{s.id}</NavLink></td><td>{s.project_name||`Project ${s.project_id}`}</td><td className="mono">{s.base_url}</td><td><Status value={s.status}/></td><td><div className="mini-progress"><i style={{width:`${s.progress}%`}}/></div></td><td>{fmtDate(s.created_at)}</td></tr>)}{!scans.length&&<tr><td colSpan={6} className="empty">No scans yet.</td></tr>}</tbody></table></div>}

function Projects(){
 const [projects,setProjects]=useState<Project[]>([]); const [show,setShow]=useState(false); const [form,setForm]=useState({name:'',description:'',spec_text:''}); const [error,setError]=useState('');
 const load=()=>api.projects().then(setProjects); useEffect(()=>{load()},[]);
 const submit=async(e:any)=>{e.preventDefault();setError('');try{await api.createProject(form);setShow(false);setForm({name:'',description:'',spec_text:''});load()}catch(err:any){setError(err.message)}};
 const file=(f?:File)=>{if(!f)return; const r=new FileReader(); r.onload=()=>setForm(x=>({...x,spec_text:String(r.result||''),name:x.name||f.name.replace(/\.(ya?ml|json)$/i,'')}));r.readAsText(f)};
 return <><Header eyebrow="Inventory" title="API projects" subtitle="Store specifications and inspect the attack surface before any traffic is sent." action={<button className="button primary" onClick={()=>setShow(!show)}><Plus size={16}/>New project</button>}/>{show&&<form className="panel form" onSubmit={submit}><div className="form-grid"><label>Name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></label><label>Description<input value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label></div><label>OpenAPI JSON/YAML<textarea rows={12} value={form.spec_text} onChange={e=>setForm({...form,spec_text:e.target.value})} placeholder="Paste your OpenAPI document here…" required/></label><div className="form-actions"><label className="button subtle"><FileJson size={16}/>Upload spec<input type="file" accept=".yaml,.yml,.json" hidden onChange={e=>file(e.target.files?.[0])}/></label><button className="button primary">Create project</button></div>{error&&<div className="error">{error}</div>}</form>}<div className="cards-grid">{projects.map(p=><NavLink className="project-card" to={`/projects/${p.id}`} key={p.id}><div className="project-icon"><FileJson/></div><div><h3>{p.name}</h3><p>{p.description||'No description'}</p><div className="project-meta"><span>{p.spec_info?.operation_count??0} operations</span><span>{p.spec_info?.openapi||'OpenAPI'}</span></div></div></NavLink>)}</div></>
}

function ProjectDetail(){const {id}=useParams(); const pid=Number(id); const [project,setProject]=useState<Project|null>(null);const [ops,setOps]=useState<Operation[]>([]);useEffect(()=>{api.project(pid).then(setProject);api.operations(pid).then(setOps)},[pid]); return <><Header eyebrow="Attack surface" title={project?.name||'Project'} subtitle={`${project?.spec_info?.title||'API'} · ${ops.length} discovered operations`} action={<NavLink className="button primary" to={`/scan/new?project=${pid}`}><Radar size={16}/>Scan project</NavLink>}/><section className="panel"><div className="table-wrap"><table><thead><tr><th>Method</th><th>Path</th><th>Auth</th><th>Inputs</th><th>Summary</th></tr></thead><tbody>{ops.map((o,i)=><tr key={i}><td><span className={`method method-${o.method.toLowerCase()}`}>{o.method}</span></td><td className="mono">{o.path}</td><td>{o.security_required?'Required':'Public'}</td><td>{o.parameters.length+(o.has_request_body?1:0)}</td><td>{o.summary||'—'}</td></tr>)}</tbody></table></div></section></>}

function NewScan(){
 const nav=useNavigate(); const params=new URLSearchParams(location.search); const [projects,setProjects]=useState<Project[]>([]); const [error,setError]=useState(''); const [form,setForm]=useState<any>({project_id:Number(params.get('project')||0),base_url:'http://127.0.0.1:9000',bearer_token:'',secondary_bearer_token:'',extra_headers:'',allowed_hosts:'',alternate_ids:'user_id=2',requests_per_second:2,max_requests:250,allow_write_methods:false,verify_tls:true,authorization_ack:false});
 useEffect(()=>{api.projects().then(ps=>{setProjects(ps);if(!form.project_id&&ps[0])setForm((x:any)=>({...x,project_id:ps[0].id}))})},[]);
 const parseAlt=()=>Object.fromEntries(form.alternate_ids.split(',').map((x:string)=>x.trim()).filter(Boolean).map((x:string)=>x.split('=',2)).filter((x:string[])=>x.length===2));
 const parseHeaders=()=>Object.fromEntries(form.extra_headers.split(',').map((x:string)=>x.trim()).filter(Boolean).map((x:string)=>x.split('=',2)).filter((x:string[])=>x.length===2));
 const submit=async(e:any)=>{e.preventDefault();setError('');try{const scan=await api.createScan({...form,extra_headers:parseHeaders(),allowed_hosts:form.allowed_hosts.split(',').map((x:string)=>x.trim()).filter(Boolean),alternate_ids:parseAlt(),requests_per_second:Number(form.requests_per_second),max_requests:Number(form.max_requests)});nav(`/scans/${scan.id}`)}catch(err:any){setError(err.message)}};
 return <><Header eyebrow="Controlled testing" title="Configure scan" subtitle="Scope the target explicitly, keep rates bounded, and opt in separately to state-changing methods."/><form className="panel form" onSubmit={submit}><div className="form-grid"><label>Project<select value={form.project_id} onChange={e=>setForm({...form,project_id:Number(e.target.value)})}>{projects.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><label>Base URL<input value={form.base_url} onChange={e=>setForm({...form,base_url:e.target.value})} placeholder="https://api.example.com" required/></label><label>Primary bearer token<input type="password" value={form.bearer_token} onChange={e=>setForm({...form,bearer_token:e.target.value})} placeholder="Optional; never persisted"/></label><label>Secondary bearer token<input type="password" value={form.secondary_bearer_token} onChange={e=>setForm({...form,secondary_bearer_token:e.target.value})} placeholder="Optional; improves BOLA validation"/></label><label>Additional headers<input value={form.extra_headers} onChange={e=>setForm({...form,extra_headers:e.target.value})} placeholder="X-API-Key=demo, X-Tenant=test"/></label><label>Exact allowed remote hosts<input value={form.allowed_hosts} onChange={e=>setForm({...form,allowed_hosts:e.target.value})} placeholder="api.example.com, staging-api.example.com"/></label><label>Alternate object IDs<input value={form.alternate_ids} onChange={e=>setForm({...form,alternate_ids:e.target.value})} placeholder="user_id=2, order_id=101"/></label><label>Requests / second<input type="number" min="0.1" max="10" step="0.1" value={form.requests_per_second} onChange={e=>setForm({...form,requests_per_second:e.target.value})}/></label><label>Request budget<input type="number" min="1" max="2000" value={form.max_requests} onChange={e=>setForm({...form,max_requests:e.target.value})}/></label></div><div className="checks"><label><input type="checkbox" checked={form.allow_write_methods} onChange={e=>setForm({...form,allow_write_methods:e.target.checked})}/><span><b>Allow state-changing methods</b><small>POST, PUT, PATCH and DELETE are skipped by default.</small></span></label><label><input type="checkbox" checked={form.verify_tls} onChange={e=>setForm({...form,verify_tls:e.target.checked})}/><span><b>Verify TLS certificates</b><small>Recommended for all non-lab targets.</small></span></label><label className="authorization"><input type="checkbox" checked={form.authorization_ack} onChange={e=>setForm({...form,authorization_ack:e.target.checked})}/><span><b>I own this API or have explicit authorization to test it.</b><small>Scanning is blocked until this is confirmed.</small></span></label></div>{error&&<div className="error">{error}</div>}<div className="form-actions right"><button className="button primary" disabled={!form.authorization_ack}><Play size={16}/>Start authorized scan</button></div></form></>
}

function Scans(){const [scans,setScans]=useState<Scan[]>([]);useEffect(()=>{api.scans().then(setScans)},[]);return <><Header eyebrow="History" title="Scans" subtitle="Every bounded audit run and its completion state." action={<NavLink className="button primary" to="/scan/new"><Plus size={16}/>New scan</NavLink>}/><section className="panel"><ScanTable scans={scans}/></section></>}

function FindingsTable({items}:{items:Finding[]}){return <div className="table-wrap"><table><thead><tr><th>Severity</th><th>Finding</th><th>Endpoint</th><th>Confidence</th><th>Category</th></tr></thead><tbody>{items.map(f=><tr key={f.id}><td><Severity value={f.severity}/></td><td><b>{f.title}</b><small className="row-sub">{f.owasp}</small></td><td className="mono">{f.method} {f.endpoint}</td><td>{f.confidence}</td><td>{f.category.replaceAll('_',' ')}</td></tr>)}{!items.length&&<tr><td colSpan={5} className="empty">No findings yet.</td></tr>}</tbody></table></div>}

function ScanDetail(){
 const {id}=useParams();const sid=Number(id);const [scan,setScan]=useState<Scan|null>(null);const [findings,setFindings]=useState<Finding[]>([]); const load=()=>{api.scan(sid).then(setScan);api.findings(sid).then(setFindings)};
 useEffect(()=>{load();const t=setInterval(load,1800);return()=>clearInterval(t)},[sid]);
 const stats=scan?.stats||{};return <><Header eyebrow="Scan workspace" title={`Scan #${sid}`} subtitle={`${scan?.project_name||'Project'} · ${scan?.base_url||''}`} action={<div className="actions"><a className="button subtle" target="_blank" href={api.reportJson(sid)}>JSON</a><a className="button primary" target="_blank" href={api.reportHtml(sid)}>HTML report</a></div>}/><div className="scan-banner"><div><Status value={scan?.status||'queued'}/><b>{scan?.progress||0}% complete</b></div><div className="progress"><i style={{width:`${scan?.progress||0}%`}}/></div>{scan?.error&&<div className="error">{scan.error}</div>}</div><div className="stats"><StatCard label="Discovered" value={stats.endpoints_discovered||0} icon={ScanSearch}/><StatCard label="Scanned" value={stats.endpoints_scanned||0} icon={Gauge}/><StatCard label="Requests" value={stats.requests_sent||0} icon={Activity}/><StatCard label="Findings" value={findings.length} icon={AlertTriangle}/></div><section className="panel"><div className="panel-title"><div><span className="eyebrow">Evidence</span><h2>Findings</h2></div></div><FindingsTable items={findings}/></section></>
}

function Findings(){const [items,setItems]=useState<Finding[]>([]);const [filter,setFilter]=useState('');useEffect(()=>{api.allFindings(filter||undefined).then(setItems)},[filter]);return <><Header eyebrow="Triage" title="Findings" subtitle="Review automated evidence, confidence, OWASP mapping, and remediation guidance."/><div className="filter-row"><button className={!filter?'active':''} onClick={()=>setFilter('')}>All</button>{sevOrder.map(s=><button key={s} className={filter===s?'active':''} onClick={()=>setFilter(s)}>{s}</button>)}</div><section className="panel"><FindingsTable items={items}/></section></>}

export default Layout;
